# Seed
seed: 0

# Model
model: 'resnet_18'

# 50, 75%, 90% Static baselines
maskopt: 'static'
maskopt_sparsity: 
  - 0.50
  - 0.75
  - 0.90
maskopt_mask_distribution: 'uniform'
maskopt_mask_init_method: 'random'

# Sparse-IFT
sift_scaling: true
sift_family: 'sparse_wide'
