# Seed
seed: 0

# Model
model: 'resnet_18'
block_name: 'BlockISOFlopParallel'

# 50, 75%, 90% RigL baselines
maskopt: 'rigl'
maskopt_sparsity: 
  - 0.50
  - 0.75
  - 0.90
maskopt_mask_distribution: 'uniform'
maskopt_mask_init_method: 'random'
maskopt_drop_fraction: 0.3
maskopt_frequency: 100

# Sparse-IFT
sift_scaling: true
sift_family: 'sparse_parallel'
