# model
model: 'resnet_34'
# seed
seed: 0
# sparsity
maskopt: 'rigl'
maskopt_sparsity:
  - 0.5
  # - 0.75
  # - 0.9
maskopt_mask_distribution: 'uniform'
maskopt_mask_init_method: 'random'
maskopt_drop_fraction: 0.3
maskopt_frequency: 100
# sift
sift_scaling: true
sift_family: 'sparse_wide'
flop_budget: 7355270501
